# Default values for key.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  toxiproxy:
    repository: shopify/toxiproxy
    tag: 2.1.3
    pullPolicy: Always
  resiproxy:
    repository: marqub/resiproxy
    tag: dev
    pullPolicy: Always  
service:
  toxiproxy:
    name: toxiproxy
    type: NodePort
    externalPort: 8474
    internalPort: 8474
  resiproxy:
    name: resiproxy
    type: NodePort
    externalPort: 8080
    internalPort: 8080
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - resiproxy.resiliency-testing.com
