apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ .Values.service.resiproxy.name }}
data:
  TOXIPROXY_NAME: {{ template "toxiproxy.fullname" . }}
  TOXIPROXY_NAMESPACE: {{ .Release.Namespace }}
  TOXIPROXY_SCHEME: http
  TOXIPROXY_PORT: "{{ .Values.service.toxiproxy.externalPort }}"